import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1>Home Page!</h1>
        <Link  href="/upload">upload page</Link> <br></br>
        <Link  href="/search">search page</Link>
      </main>
    </>
  )
}
